-- Auto-generated NPC record catalog (AMM TweakDB export, 629 records).
-- modules/npcdata -- exposes CC.npcRecords = { { name=, record= }, ... }
-- Drop this file in your mod's modules/ folder and add "modules/npcdata"
-- to the MODULES list in init.lua (already done if you took the init.lua edit).
return function(CC)
    CC.npcRecords = {
        { name = "Judy", record = "Character.Judy" },
        { name = "Panam", record = "Character.Panam" },
        { name = "Rogue", record = "Character.Rogue" },
        { name = "Alt", record = "Character.Alt" },
        { name = "Jackie", record = "Character.Jackie" },
        { name = "Hanako", record = "Character.Hanako" },
        { name = "River", record = "Character.Sobchak" },
        { name = "River (VR)", record = "Character.sq029_sobchak_vr" },
        { name = "Goro Takemura", record = "Character.Takemura" },
        { name = "Adam Smasher", record = "Character.Smasher" },
        { name = "Cheri from Clouds", record = "Character.q105_yakuza_manager" },
        { name = "Blue Moon", record = "Character.sq017_blue_moon" },
        { name = "Red Menace", record = "Character.sq017_red_menace" },
        { name = "Purple Force", record = "Character.sq017_purple_force" },
        { name = "Evelyn", record = "Character.Evelyn" },
        { name = "8ug8ear", record = "Character.sts_hey_rey_09_tobias" },
        { name = "Skye", record = "Character.q105_doll_female_skye" },
        { name = "Lizzy", record = "Character.Lizzy_Wizzy" },
        { name = "Ruby", record = "Character.sq031_streapper" },
        { name = "Anna Hamill", record = "Character.sts_wat_kab_08_dave_hamill" },
        { name = "Sandra Dorsett", record = "Character.mq024_sandra_combatable" },
        { name = "Claire", record = "Character.Claire" },
        { name = "Emmerick Bronson", record = "Character.Emmerick" },
        { name = "Elizabeth Peralez", record = "Character.Elizabeth_Peralez" },
        { name = "Jefferson Peralez", record = "Character.Jefferson_Peralez" },
        { name = "Maiko", record = "Character.Maiko" },
        { name = "Roxanne Sumner", record = "Character.Roxanne" },
        { name = "Tbug", record = "Character.Tbug" },
        { name = "Dr. Yawen Packard", record = "Character.sq021_dr_mitsuko" },
        { name = "Misty", record = "Character.Misty" },
        { name = "Joss Kutcher", record = "Character.sq021_joss" },
        { name = "Dorian Kutcher", record = "Character.sq021_joss_kid_boy" },
        { name = "Dorian (VR)", record = "Character.sq029_joss_kid_boy_vr" },
        { name = "Monique Kutcher", record = "Character.sq021_joss_kid_girl" },
        { name = "Monique (VR)", record = "Character.sq029_joss_kid_girl_vr" },
        { name = "Randy Kutcher", record = "Character.sq021_randy" },
        { name = "Anthony Harris", record = "Character.sq021_meatman" },
        { name = "Mr. Blue Eyes (G-Man)", record = "Character.q203_mr_x" },
        { name = "Ozob", record = "Character.Ozob" },
        { name = "Ziggy Q", record = "Character.ziggy_q" },
        { name = "Shaitan", record = "Character.q101_blackhand_minion" },
        { name = "Hal Cantos", record = "Character.sts_wat_nid_01_hal_cantos" },
        { name = "Theo Price", record = "Character.mq037_girlfriend" },
        { name = "Rachel", record = "Character.sq023_rachel" },
        { name = "Gloria El Ahmar", record = "Character.sq023_gloria" },
        { name = "Ruth Dzeng", record = "Character.ruth_dzeng" },
        { name = "Rodrigo Martinez", record = "Character.rodrigo_martinez" },
        { name = "Bill Jablonsky", record = "Character.sq023_bill_jablonsky" },
        { name = "Joshua", record = "Character.sq023_joshua" },
        { name = "Donnie Carter", record = "Character.sq012_peralez_driver" },
        { name = "John Lucas", record = "Character.sq012_lucas" },
        { name = "Daniel Lark", record = "Character.sq012_lark" },
        { name = "Mayor Lucius Rhyne", record = "Character.sq012_lucius_rhyne" },
        { name = "Deputy Mayor Holt", record = "Character.sq012_weldon_holt" },
        { name = "Agent Orange", record = "Character.sq017_agent_orange" },
        { name = "Rick Martinez", record = "Character.q000_kid_parking_security" },
        { name = "Jack Mausser", record = "Character.sts_cct_dtn_02_dozy" },
        { name = "Lucas Fletcher", record = "Character.q000_basketballer_03_ma" },
        { name = "Benjamin Stone", record = "Character.q000_basketballer_02_mb" },
        { name = "Ernie Hawkins", record = "Character.q000_basketballer_01_ma" },
        { name = "Rosalind Myers", record = "Character.rosalind_myers" },
        { name = "Josh Kavorkin", record = "Character.josh_kavorkin" },
        { name = "Spider Murphy", record = "Character.q101_spider_murphy" },
        { name = "Martin Tin", record = "Character.q101_parasite" },
        { name = "Huscle", record = "Character.q101_toten_guard" },
        { name = "Milt Nauman", record = "Character.q108_ripper" },
        { name = "Santiago Aldecaldo", record = "Character.Santiago" },
        { name = "Lyle Thompson", record = "Character.Thompson" },
        { name = "Johnnie Peterson", record = "Character.q108_barman_m_01" },
        { name = "Annie Capolino", record = "Character.q108_crowd_f_02_drugs" },
        { name = "Classified", record = "Character.q108_crowd_f_01_dancefloor_chat" },
        { name = "Yishen Rhee", record = "Character.q108_crowd_f_02_vending_machine" },
        { name = "Axel Mankievicz", record = "Character.q108_mercenary_mb_02_drinking" },
        { name = "Melissa Wellingham", record = "Character.q108_barman_f_01" },
        { name = "Freddie Burns", record = "Character.q108_bouncer_entrance" },
        { name = "Oleg Darkevich", record = "Character.Dex_bodyguard" },
        { name = "Certo Esquerdo", record = "Character.mq025_twin_01" },
        { name = "Esquerdo Certo", record = "Character.mq025_twin_02" },
        { name = "Peter 'PJ' Sampson", record = "Character.sq024_dominic" },
        { name = "Oswald 'Woodman' Forrest", record = "Character.sq026_woodman" },
        { name = "Steve Sanchez", record = "Character.Steve" },
        { name = "Tiny Mike", record = "Character.sts_wat_kab_01_tiny_mike" },
        { name = "Flavio dos Santos", record = "Character.sts_std_rcr_03_flavio" },
        { name = "Roh Chi-Won", record = "Character.sts_wat_lch_03_ricky_wu" },
        { name = "Regina Jones", record = "Character.reggie" },
        { name = "Wakako Okada", record = "Character.wakako_okada" },
        { name = "Dakota Smith", record = "Character.dakota_smith" },
        { name = "Dexter DeShawn", record = "Character.Dexter" },
        { name = "Mikhail Akulov", record = "Character.sts_wat_kab_04_tanyimu" },
        { name = "Muamar Reyes", record = "Character.muamar_reyes" },
        { name = "Sebastian Ibarra", record = "Character.Padre" },
        { name = "Mr. Hands", record = "Character.mr_hands" },
        { name = "Viktor Vektor", record = "Character.Victor_Vector" },
        { name = "Finn Gerstatt", record = "Character.Fingers" },
        { name = "Charles Bucks", record = "Character.wat_kab_ripperdoc_02" },
        { name = "Cassius Ryder", record = "Character.wat_nid_ripperdoc_01" },
        { name = "Robert Rainwater", record = "Character.wat_kab_ripperdoc_03" },
        { name = "Lucy Thackery", record = "Character.sts_wat_kab_02_lucy" },
        { name = "Shady Ripperdoc", record = "Character.mq040_ripperdoc" },
        { name = "Michiko", record = "Character.Michiko" },
        { name = "Saburo Arasaka", record = "Character.Saburo" },
        { name = "Yorinobu", record = "Character.Yorinobu" },
        { name = "Oda (Boss version)", record = "Character.Cyberninja_Oda" },
        { name = "Anders Hellman", record = "Character.Haru_Kasai" },
        { name = "Stanley Judith", record = "Character.q000_corpo_arasaka_m_receptionist" },
        { name = "Frank Nostra", record = "Character.q000_corpo_friend" },
        { name = "Arthur Jenkins", record = "Character.q000_corpo_jenkins" },
        { name = "Carter Smith", record = "Character.q000_corpo_assistant" },
        { name = "Alois Daquin", record = "Character.sts_wat_kab_05_aloise_daquin" },
        { name = "Harry", record = "Character.Arasaka_Coworker" },
        { name = "Kaoru", record = "Character.q000_kid_parking_kaoru" },
        { name = "Toshiro", record = "Character.q108_toshiro" },
        { name = "Akira", record = "Character.q108_akira" },
        { name = "Arasaka Ninja", record = "Character.troyAssassinTemplate" },
        { name = "Arasaka Soldier", record = "Character.q112_parade_officer_soldier1_ranged3_masamune_mah_rare" },
        { name = "Female Arasaka Corpo", record = "Character.q000_corpo_arasaka_f_corporate" },
        { name = "Arasaka Corpo", record = "Character.q000_corpo_arasaka_m_corporate" },
        { name = "Female Guard", record = "Character.q000_corpo_arasaka_security_wa" },
        { name = "Male Guard", record = "Character.q000_corpo_arasaka_security" },
        { name = "Male Agent 2020", record = "Character.q108_arasaka_m_shotgun" },
        { name = "Female Agent 2020", record = "Character.q108_arasaka_f_rifle_Alpha" },
        { name = "Soulkiller", record = "Character.q101_soulkiller_fem" },
        { name = "Sumo", record = "Character.q000_kid_parking_corpo_bodyguard" },
        { name = "Classified Data", record = "Character.q000_corpo_arasaka_m_cleaner" },
        { name = "Arasaka Minotaur", record = "Character.q114_arasaka_netnest_mech_friendly_quest" },
        { name = "Arasaka Robot", record = "Character.q115_arasaka_jungle_droid_rifle" },
        { name = "Octant", record = "Character.arasaka_base_drone_octant" },
        { name = "Saul", record = "Character.Saul" },
        { name = "Mitch", record = "Character.Mitch" },
        { name = "Cassidy", record = "Character.Cassidy" },
        { name = "Scorpion", record = "Character.Scorpion" },
        { name = "Carol", record = "Character.Carol" },
        { name = "Female Nomad", record = "Character.CitizenAldecaldosFemaleTeenager" },
        { name = "Male Aldecado Grunt", record = "Character.sq024_luigi" },
        { name = "Female Aldecado Grunt", record = "Character.aldecaldos_grunt2_sniper2_sor22_wa_elite" },
        { name = "Male Nomad Grunt", record = "Character.sq027_nomads_defense_male" },
        { name = "Sheriff Andrew Jones", record = "Character.California_Sheriff" },
        { name = "California Mechanic", record = "Character.California_Mechanic" },
        { name = "Guadalupe Alejandra Welles", record = "Character.Mama_Welles" },
        { name = "Pepe Najarro", record = "Character.Elcoyote_Barman" },
        { name = "Lucas Palmer", record = "Character.q000_kid_bar_patron_male_01" },
        { name = "Daniel Duarte", record = "Character.q000_kid_bar_patron_male_02" },
        { name = "Gustav", record = "Character.q000_kid_bar_waitress" },
        { name = "Mateo Lorenzo", record = "Character.q000_kid_bar_patron_male_03" },
        { name = "Irene Hermoso", record = "Character.q000_kid_bar_woman" },
        { name = "Big Joe", record = "Character.q000_kid_bar_kirks_bodyguard" },
        { name = "Kirk Sawyer", record = "Character.fixer_kirk" },
        { name = "Camilo Castilla", record = "Character.q000_kid_coyote_staffer" },
        { name = "Sofia Rossi", record = "Character.q000_kid_hooker" },
        { name = "Marcus Barros", record = "Character.q000_kid_marcus" },
        { name = "César Diego Ruiz", record = "Character.mq025_cesar" },
        { name = "Micaela Ruiz", record = "Character.mq025_cesars_girl" },
        { name = "Valentino Bouncer", record = "Character.q000_kid_bar_bouncer" },
        { name = "Valentino Female", record = "Character.arr_valentinos_grunt2_ranged2_ajax_wa" },
        { name = "Valentino Male", record = "Character.dtn_valentinos_grunt2_ranged2_ajax_ma" },
        { name = "Placide", record = "Character.Placide" },
        { name = "Maman Brigitte", record = "Character.Voodoo_Queen" },
        { name = "Emilie Massenat", record = "Character.q110_placide_girlfriend" },
        { name = "Ertha Ojasma", record = "Character.q110_grann_ertha" },
        { name = "Noel Ducael", record = "Character.q110_sermon_leader" },
        { name = "Voodoo Boy", record = "Character.mq025_voodooboy_male" },
        { name = "Voodoo Girl", record = "Character.mq025_voodooboy_female" },
        { name = "Taki Kenmochi", record = "Character.sts_wat_kab_107_taki_kenmochi" },
        { name = "Hiromi Sato", record = "Character.sq026_hiromi" },
        { name = "Jotaro Shobo", record = "Character.sts_wat_kab_07_jotaro" },
        { name = "Female Biker", record = "Character.dtn_tyger_claws_biker1_ranged1_nue_wa" },
        { name = "Male Biker", record = "Character.ma_wat_kab_06_shard_ganger" },
        { name = "Female Gangster", record = "Character.jpn_tyger_claws_gangster1_melee1_knife_wa" },
        { name = "Male Gangster", record = "Character.bls_se_tyger_claws_gangster3_ranged3_sidewinder_ma" },
        { name = "Rhino", record = "Character.mq025_rhino" },
        { name = "Sasquatch", record = "Character.main_boss_sasquatch" },
        { name = "Razor Hugh", record = "Character.mq025_razor" },
        { name = "Mauler", record = "Character.dtn_animals_bouncer2_melee2_fists_mb" },
        { name = "Raptor", record = "Character.animals_grunt2_ranged2_overture_mb" },
        { name = "Female Undertaker", record = "Character.sq012_animal_officer_beta_female" },
        { name = "Male Undertaker", record = "Character.sq012_animal_hammer" },
        { name = "Animals Elite", record = "Character.cvi_animals_elite2_hmelee2_fists_mba_rare" },
        { name = "Sarge", record = "Character.rcr_sixthstreet_veteran3_ranged2_ajax_ma" },
        { name = "Veteran", record = "Character.sts_wbr_hil_06_wyatt_alken" },
        { name = "Female Soldier", record = "Character.sts_std_arr_06_sixthstreet_patrol2_ranged2_ajax_wa" },
        { name = "Female Member", record = "Character.sixthstreet_menace1_fshotgun2_tactician_wa_rare" },
        { name = "Gang Member", record = "Character.rcr_sixthstreet_menace1_shotgun2_igla_ma" },
        { name = "Royce", record = "Character.Royce" },
        { name = "Dum Dum", record = "Character.DumDum" },
        { name = "Dietlinde", record = "Character.wat_nid_foodshop_02" },
        { name = "Patricia", record = "Character.sq011_patricia" },
        { name = "Brick", record = "Character.Brick" },
        { name = "Female Maelstrom Grunt", record = "Character.sts_std_arr_09_enemy_rifle" },
        { name = "Male Maelstrom Grunt", record = "Character.mq026_mal_handgunner" },
        { name = "Maelstrom Strong", record = "Character.sq031_maelstrom_strong_shotgunner_elite" },
        { name = "Maelstrom Cultist", record = "Character.ma_wat_nid_15_maelstrom_dying" },
        { name = "Susanna Quinn", record = "Character.q105_lizzies_boss" },
        { name = "Mateo Thiago", record = "Character.lizzies_barman" },
        { name = "Mox Waitress", record = "Character.MoxWaitress" },
        { name = "Mox Bouncer", record = "Character.sts_wat_nid_01_lizzie" },
        { name = "Female Mox Grunt", record = "Character.the_mox_1_ranged1_lexington_wa" },
        { name = "Male Mox Grunt", record = "Character.q000_lizzies_mox_male" },
        { name = "Female Mox Elite", record = "Character.the_mox_elite3_fmelee3_mantis_wa_elite" },
        { name = "Henry", record = "Character.Henry" },
        { name = "Nancy", record = "Character.Nancy" },
        { name = "Denny", record = "Character.Denny" },
        { name = "Kerry", record = "Character.Kerry" },
        { name = "Nix", record = "Character.Nix" },
        { name = "Queen of the Stoop", record = "Character.q101_audience_female" },
        { name = "Fangirl", record = "Character.q108_samurai_fan_light_crowd_fa" },
        { name = "Fanboy", record = "Character.q101_audience_male" },
        { name = "Roadie", record = "Character.q101_samurai_band_staff_male" },
        { name = "Melissa Rory", record = "Character.mq030_melisa" },
        { name = "Barry", record = "Character.mq010_barry" },
        { name = "Juan Mendez", record = "Character.mq010_policeman" },
        { name = "Nadia Petrova", record = "Character.mq010_policewoman" },
        { name = "Officer Vasquez", record = "Character.sq023_vasquez" },
        { name = "Det. Harold Han", record = "Character.sq012_det_yu" },
        { name = "Investigator", record = "Character.nok_ncpd_investigator_officer_omaha_ma" },
        { name = "Female Police", record = "Character.prevention_police_handgun_wa" },
        { name = "Male Police", record = "Character.prevention_police_handgun_ma" },
        { name = "MaxTac Soldier", record = "Character.mq030_max_tac_no_combat" },
        { name = "Shotgun Enforcer", record = "Character.nok_ncpd_enforcer_shotgun2_tactician_ma_rare" },
        { name = "Studio Security", record = "Character.sq023_guard" },
        { name = "NCPD Minotaur", record = "Character.ncpd_minotaur" },
        { name = "Bryce", record = "Character.q110_netwatch_agent" },
        { name = "Netwatch Agent", record = "Character.cpz_netwatch_agent_netrunner3_omaha_elite" },
        { name = "Support", record = "Character.sq024_tt" },
        { name = "Paramedic", record = "Character.sq021_traumateam" },
        { name = "Naked Helmet Guy", record = "Character.q001_lover_for_male_v" },
        { name = "Male Medic", record = "Character.trauma_rare_officer_chao_ma" },
        { name = "Officer", record = "Character.kab_trauma_rare_officer_chao_ma" },
        { name = "Trauma Team Soldier", record = "Character.kab_trauma_soldier_ranged2_dian_ma" },
        { name = "Meredith Stout", record = "Character.Stout" },
        { name = "Anthony Gilchrist", record = "Character.Gilchrist" },
        { name = "Militech Enforcer", record = "Character.gle_militech_enforcer3_gunner3_HMG_mb_elite" },
        { name = "Ranger", record = "Character.gle_militech_ranger2_ranged2_ajax_ma" },
        { name = "Tech", record = "Character.hil_militech_tech_grenadier2_omaha_ma_rare" },
        { name = "Border Patrol", record = "Character.bls_se5_border_guards" },
        { name = "Militech Minotaur", record = "Character.q003_militech_mech" },
        { name = "Militech Drone", record = "Character.sts_wat_kab_101_drone_security" },
        { name = "Kang Tao Soldier", record = "Character.q104_gas_station_kangtao_shotgun_tier2" },
        { name = "Pilot", record = "Character.q104_av_pilot" },
        { name = "Gunner", record = "Character.q104_gas_station_kangtao_shotgun_tier3" },
        { name = "Kang Tao Robot", record = "Character.q104_arasaka_av_droid" },
        { name = "Kang Tao Drone", record = "Character.q104_pp_drones" },
        { name = "Anna Nox", record = "Character.sts_wat_nid_01_cyberpsycho" },
        { name = "Rose Horrigan", record = "Character.rcr_05_cyberpsycho" },
        { name = "Dao Hyunh", record = "Character.ma_hey_spr_04_cyberpsycho" },
        { name = "Tamara Cosby", record = "Character.ma_std_arr_06_cyberpsycho" },
        { name = "Zaria Hughes", record = "Character.ma_wat_nid_15_psycho" },
        { name = "Lieutenant Mower", record = "Character.ma_wat_kab_08_cyberpsycho" },
        { name = "Gaston Phillips", record = "Character.ma_hey_spr_06_cyberpsycho" },
        { name = "Alec Johnson", record = "Character.ma_wat_lch_06_cyberpsycho" },
        { name = "Chase Coley", record = "Character.ma_std_rcr_11_cyberpsycho" },
        { name = "Russell Greene", record = "Character.ma_bls_ina_se1_08_cyberpsycho" },
        { name = "Matt Liaw", record = "Character.ma_wat_kab_02_cyberpsycho" },
        { name = "Ben DeBaillon", record = "Character.ma_pac_cvi_15_cyberpsycho" },
        { name = "Norio Akuhara", record = "Character.ma_cct_dtn_07_cyberpsycho" },
        { name = "Cedric Muller", record = "Character.ma_cct_dtn_03_cyberpsycho" },
        { name = "Lely Hein Goon", record = "Character.ma_wat_nid_22_monk" },
        { name = "Ellis Carter", record = "Character.ma_wat_nid_03_shard_psycho" },
        { name = "Hideo Kojima", record = "Character.q005_hideyoshi_oshima" },
        { name = "Alanah Pearce", record = "Character.mq042_nomad_alice" },
        { name = "Garry The Prophet (CohhCarnage)", record = "Character.mq026_prophet" },
        { name = "Jesse Cox", record = "Character.mq012_stud" },
        { name = "Nadezhda Tiurina", record = "Character.sts_wat_kab_04_ryoko" },
        { name = "Roy Batty (Blade Runner)", record = "Character.batty" },
        { name = "Female Luxury Joytoy", record = "Character.hey_gle_prostitute_female" },
        { name = "Hotel Escort", record = "Character.q005_hotel_escort" },
        { name = "Tube Dancer", record = "Character.ServiceTubeDancerFemale" },
        { name = "Female Sexworker", record = "Character.SexworkerFemale" },
        { name = "Female Joytoy", record = "Character.wbr_jpn_prostitute_female" },
        { name = "Hood Hottie", record = "Character.NightlifeWoman" },
        { name = "Mallrat", record = "Character.Mallrat" },
        { name = "Truck Driver", record = "Character.sq023_kaukaz_driver" },
        { name = "Male Actor", record = "Character.sq023_soldier_one" },
        { name = "Female Protester", record = "Character.sq023_crowd_wa_downtown" },
        { name = "Bartender", record = "Character.q115_restaurant_bartender" },
        { name = "Waitress Restaurant", record = "Character.q115_restaurant_waitress" },
        { name = "Rich Woman", record = "Character.CitizenRichFemale" },
        { name = "Housekeeper", record = "Character.q005_hotel_cleaning_lady" },
        { name = "Female Lowlife", record = "Character.LowlifeWoman" },
        { name = "Female Creole", record = "Character.CreoleWoman" },
        { name = "Female Freak", record = "Character.FreakFemale" },
        { name = "Female Slacker", record = "Character.SlackerFemale" },
        { name = "Male Slacker", record = "Character.SlackerMale" },
        { name = "Male Homeless Quest", record = "Character.q000_kid_homeless" },
        { name = "Janitor", record = "Character.q000_kid_embers_worker" },
        { name = "Conspiracy Soldier", record = "Character.sq006_conspiracy_soldier" },
        { name = "Boxing Android", record = "Character.boxingrobot_easy" },
        { name = "Sandra Dorsett (Explosive)", record = "Character.q001_scavenger_girl" },
        { name = "Cyberpunk Female Rifle", record = "Character.afterlife_merc_generic_medium_range_w_hard" },
        { name = "Workout Jock Female", record = "Character.WorkoutFemale" },
        { name = "Workout Jock Big Male", record = "Character.WorkoutMaleBig" },
        { name = "Morning Crowd Female", record = "Character.TenantWoman" },
        { name = "Morning Crowd Male", record = "Character.TenantMale" },
        { name = "Cyberpunk Female", record = "Character.q005_afterlife_crowd_cyberpunk_female" },
        { name = "Cyberpunk Big Male", record = "Character.q005_afterlife_crowd_mercenary_male_big" },
        { name = "Cyberpunk Male", record = "Character.q005_afterlife_crowd_cyberpunk_male" },
        { name = "Android Merc", record = "Character.q005_afterlife_crowd_mercenary_male" },
        { name = "Biker Female", record = "Character.q005_afterlife_gang_valentinos_female" },
        { name = "Biker Male", record = "Character.q005_afterlife_gang_tyger_claw_male" },
        { name = "Dino Dinovic", record = "Character.dyno" },
        { name = "Aaron McCarlson", record = "Character.sts_wat_nid_07_aaron" },
        { name = "Hwangbo Dong-Gun", record = "Character.nid_03_haruo" },
        { name = "Activist", record = "Character.activist" },
        { name = "Lizzies Waitress", record = "Character.lizzies_mox_female_waitress" },
        { name = "Lizzies Male Gimp", record = "Character.lizzies_mox_male_gimp" },
        { name = "Lizzies Male Gimp Jacket", record = "Character.sts_wat_kab_07_beaten_prostitute" },
        { name = "Lizzies DJ", record = "Character.lizzies_mox_female_dj" },
        { name = "Lizzies Joytoy", record = "Character.q004_prostitute" },
        { name = "Rosie Harper", record = "Character.q105_jigjig_prostitue_queue_02" },
        { name = "Griselda Martinez", record = "Character.mq028_herring_girl" },
        { name = "Stanley Media", record = "Character.Stanley_Media" },
        { name = "Hostess", record = "Character.sq017_media" },
        { name = "Female District Crowd", record = "Character.LightCrowd_charterhill_wa" },
        { name = "Nina Kraviz", record = "Character.wbr_hil_ripdoc_01" },
        { name = "Male District Crowd", record = "Character.LightCrowd_charterhill_ma" },
        { name = "Male After Work", record = "Character.CorpoMan" },
        { name = "Citizen Rich Child", record = "Character.ChildRich" },
        { name = "Female Corpo", record = "Character.CorpoWomanCorporat" },
        { name = "Male Monk", record = "Character.Monk" },
        { name = "Male Worker", record = "Character.WorkerMale" },
        { name = "Male Freak", record = "Character.FreakMale" },
        { name = "Male Vendor", record = "Character.Drinks" },
        { name = "Male Lowlife", record = "Character.LowlifeMale" },
        { name = "Producer", record = "Character.MediaWoman" },
        { name = "Female Doll", record = "Character.SexworkerFemaleDoll" },
        { name = "Male Doll", record = "Character.SexworkerMaleDoll" },
        { name = "Male Sexworker", record = "Character.SexworkerMale" },
        { name = "Female Hotel Guest", record = "Character.q005_hotel_guest_female" },
        { name = "Male Nightlife Obese", record = "Character.ObeseMaleNightlife" },
        { name = "Nonbinary Male Rich", record = "Character.NonBinaryMaleBodyPosh" },
        { name = "Nonbinary Female Nightlife", record = "Character.NonBinaryFemaleBodyNightlife" },
        { name = "Male Homeless", record = "Character.HomelessMan" },
        { name = "Female Homeless", record = "Character.HomelessFemale" },
        { name = "Female Junkie", record = "Character.JunkieFemale" },
        { name = "Female Vendor", record = "Character.Tech_Junk_Woman" },
        { name = "Aldecaldos Mechanic", record = "Character.CitizenAldecaldosMaleMechanic" },
        { name = "Tube Dancer Ground", record = "Character.ServiceDancerFemale" },
        { name = "Male Tyger Restricted", record = "Character.sa_1a_restricted" },
        { name = "Female BD Stripper", record = "Character.sts_cct_dtn_02_stripper_bd" },
        { name = "Workout Jock Male", record = "Character.WorkoutMale" },
        { name = "Lenny Nero BD Dealer", record = "Character.q105_jigjig_braindance_dealer" },
        { name = "Female Prostitute", record = "Character.q105_jigjig_prostitute_f_scanning" },
        { name = "Female Prostitute Generic", record = "Character.q105_jigjig_prostitute_f_generic" },
        { name = "Female Space Scientist", record = "Character.q201_space_scientist" },
        { name = "Militech Escort", record = "Character.sq027_militech_escort" },
        { name = "Martha Frakes", record = "Character.sts_hey_rey_01_martha" },
        { name = "Martha Young Funeral", record = "Character.sq018_rey_01_girlfriend" },
        { name = "Female Pacifica Punk", record = "Character.mq025_pacifica_female" },
        { name = "Female Voodoo Netrunner", record = "Character.q110_esc_voodooboys_netrunner3_netrunner3_quasar_wa_elite" },
        { name = "Sarah Krakosky", record = "Character.ncpd_female_spokesperson" },
        { name = "Gillean Jordan", record = "Character.gillean_jordan" },
        { name = "Juanita Tseng", record = "Character.juanita_tseng" },
        { name = "Karina Lee", record = "Character.karina_lee" },
        { name = "Actress Bushido X Grace", record = "Character.grace" },
        { name = "Actor Bushido X Gorira", record = "Character.gorira" },
        { name = "Actor Bushido X Jake", record = "Character.jake" },
        { name = "Maria Jimenez", record = "Character.maria_jimenez" },
        { name = "Kathryn OBrien", record = "Character.kathryn_obrien" },
        { name = "Female BD Crew", record = "Character.sq023_bd_crew_female_a" },
        { name = "Male BD Crew", record = "Character.sq023_bd_crew" },
        { name = "Ajax", record = "Character.sq025_mean_mls_02_ajax" },
        { name = "Hiromi Doll", record = "Character.sq026_hiromi_dolls" },
        { name = "Netrunner Male", record = "Character.sq031_maelstrom_ajax" },
        { name = "Female Maelstrom Elite", record = "Character.sq031_maelstrom_melee_female_elite" },
        { name = "Piez Waitress", record = "Character.sq023_piez_waitress" },
        { name = "Aldecaldo Driver", record = "Character.mq021_scooter_wife" },
        { name = "NCPT Technician", record = "Character.ServiceSpecialistMale" },
        { name = "Waitress Diner", record = "Character.ServiceDiningWoman" },
        { name = "Female Freak Quest", record = "Character.FreakFemale_q112" },
        { name = "Eve Martinez", record = "Character.sts_wat_kab_08_prostitute" },
        { name = "Male Sexworker Quest", record = "Character.q105_jigjig_prostitute_dosed" },
        { name = "Male Arasaka Corpo", record = "Character.CorpoManArasaka" },
        { name = "Male Lowlife Big", record = "Character.LowlifeMaleBig" },
        { name = "Female Doll Quest", record = "Character.q112_doll" },
        { name = "Female Corpo Chubby", record = "Character.WomanChubbyCorpo" },
        { name = "Male Creole", record = "Character.CreoleMan" },
        { name = "Parking Officer", record = "Character.q000_kid_parking_officer_female" },
        { name = "Female Nurse", record = "Character.NurseFemale" },
        { name = "Groupie", record = "Character.q101_samurai_band_staff_female" },
        { name = "Female Corpo Victim", record = "Character.ma_pac_cvi_08_victim_female" },
        { name = "Female Nightlife Driver", record = "Character.NightlifeFemaleDriver" },
        { name = "Female Parade Dancer", record = "Character.q112_parade_female" },
        { name = "Female Shinto Monk", record = "Character.q112_shinto_female" },
        { name = "Female Kiji Board Member", record = "Character.q113_arasaka_board_female" },
        { name = "Female Monk", record = "Character.ReligiousFemale" },
        { name = "Female Wraith", record = "Character.sq004_raffen_shiv_ganger_beta_female" },
        { name = "Valentino Sniper", record = "Character.sts_hey_spr_01_valentino_ranged_female" },
        { name = "Gottfrid Persson", record = "Character.sts_wat_nid_04_gottfrid" },
        { name = "Misha Orlova", record = "Character.ma_pac_cvi_09_scavenger_fast3_fmelee3_machete_wa_elite_Misha_Orlova" },
        { name = "Michal Glowinski", record = "Character.ma_pac_cvi_07_scavenger_grunt3_netrunner2_nova_ma_rare_Michal_Glowinski" },
        { name = "Konpeki Guard", record = "Character.arasaka_2020agent_ranged3_2020masamune_ma" },
        { name = "Tracy Phillips", record = "Character.ma_hey_gle_07_afterlife_merc_generic_medium_range_w_hard_Tracy_Phillips" },
        { name = "Rogelio Cruz", record = "Character.ma_hey_gle_02_valentinos_grunt2_ranged2_ajax_ma_Rogelio_Cruz" },
        { name = "Male Masked Security", record = "Character.sts_wat_kab_102_enemy_security_blackmasked_sniper3_grad_ma_elite" },
        { name = "Vic Vega", record = "Character.sts_wat_kab_102_enemy_security_blackmasked3_fmelee3_katana_mb_elite" },
        { name = "Female Cyborg", record = "Character.q113_estate_mansion_female_guard_rifleman" },
        { name = "Cyberpunk Merc Male", record = "Character.afterlife_merc_generic_medium_range_m_hard" },
        { name = "Male Joytoy", record = "Character.wbr_jpn_prostitute_male" },
        { name = "Male Luxury Joytoy", record = "Character.hey_gle_prostitute_male" },
        { name = "Tinnitus Male Member", record = "Character.sq011_tinitus_ma" },
        { name = "Tinnitus Female Member", record = "Character.sq011_tinitus_wa" },
        { name = "Tinnitus Crowd", record = "Character.sq011_totentanz_female_crowd" },
        { name = "Tinnitus Male Member Variant", record = "Character.sq011_tinitus_mb" },
        { name = "Female Parade Spectator", record = "Character.q112_parade_crowd_female" },
        { name = "Female Corpo Pistol", record = "Character.civilianguard_corporat_ranged1_wa" },
        { name = "Male Corpo Pistol", record = "Character.civilianguard_corporat_ranged1_ma" },
        { name = "Male JigJig Punk", record = "Character.q105_jigjig_04d_gang_m_01" },
        { name = "Female Netrunner Generic", record = "Character.generic_netrunner_netrunner_chao_wa_rare_ow_city_scene" },
        { name = "Arasaka Female Ninja Katana", record = "Character.hil_arasaka_ninja_fmelee3_katana_wa_elite" },
        { name = "Cyberpunk Female Netrunner", record = "Character.prevention_bountyhunter_netrunner_wa" },
        { name = "Female Car Seller", record = "Character.q000_hym_wa" },
        { name = "Hologram Girl", record = "Character.kab_07_hologram_girl" },
        { name = "VIP Room Hologirl", record = "Character.q004_viproom_holo" },
        { name = "JigJig Hologirl", record = "Character.q105_jigjig_hologram" },
        { name = "Pachinko Girl Hologram", record = "Character.q001_pachinko_girl" },
        { name = "Hologram Man", record = "Character.q001_hologram_man_01" },
        { name = "Hologram Man No Jacket", record = "Character.q001_hologram_man_02" },
        { name = "Hologram MaxTac Soldier", record = "Character.q001_hologram_maxtac" },
        { name = "Hologram Psycho", record = "Character.q001_hologram_psycho" },
        { name = "Hologram Male Client", record = "Character.q105_hologram_client" },
        { name = "Evelyn Parker Hologram", record = "Character.q105_hologram_evelyn" },
        { name = "Hologram Male Casual", record = "Character.sts_hey_rey_06_hologram_man" },
        { name = "Female Netrunner", record = "Character.arasaka_netrunner_netrunner2_yukimura_wa_rare" },
        { name = "Iris Tanner", record = "Character.ina_06_tanner" },
        { name = "Crispin 'Squama' Weyland", record = "Character.Weyland" },
        { name = "Wraith Robot", record = "Character.bls_se_wraiths_android_android2_pulsar_ma" },
        { name = "Wraith Ghost", record = "Character.bls_se_wraiths_ghost2_sniper2_achilles_ma_rare" },
        { name = "Wraith Ravager", record = "Character.bls_se_wraiths_grunt1_melee1_ironpipe_wa" },
        { name = "Wraith Marauder", record = "Character.bls_se_wraiths_grunt1_ranged1_nova_ma" },
        { name = "Wraith Shotgun", record = "Character.bls_se_wraiths_operator3_shotgun2_crusher_ma_rare" },
        { name = "Wraith Goliath", record = "Character.bls_se_wraiths_strong_gunner3_hmg_mb_elite" },
        { name = "Bruce Ward", record = "Character.ma_bls_ina_se1_17_outpost_miniboss" },
        { name = "Rufus McBride", record = "Character.ma_bls_se5_07_outpost_miniboss" },
        { name = "Paul Craven", record = "Character.ma_std_rcr_18_outpost_miniboss" },
        { name = "Nash Bane", record = "Character.q103_raffen_nash" },
        { name = "Wraith Female", record = "Character.q103_raffen_shiv_boss_alpha" },
        { name = "Wraith Fists", record = "Character.rcr_wraiths_strongarms_hmelee3_fists_mb_elite" },
        { name = "Hooligan Knife", record = "Character.arr_scavenger_grunt2_melee2_knife_wa" },
        { name = "Crow Ranged", record = "Character.arr_scavenger_grunt2_ranged2_pulsar_ma" },
        { name = "Vulture Elite", record = "Character.bls_se_scavenger_strong3_gunner2_defender_mb_rare" },
        { name = "Cur Machete", record = "Character.cvi_scavenger_butcher3_hmelee2_machete_mb_rare" },
        { name = "Hound Shotgun", record = "Character.cvi_scavenger_elite2_shotgun_tactician_ma" },
        { name = "Scavenger Sniper", record = "Character.lch_scavenger_elite3_sniper2_grad_ma" },
        { name = "Stanislaus Zbyszko", record = "Character.ma_pac_cvi_12_outpost_miniboss" },
        { name = "Scavenger Robot", record = "Character.ma_pac_cvi_15_droid" },
        { name = "Anton Kolev", record = "Character.ma_pac_wwd_02_outpost_miniboss" },
        { name = "Barry Alken", record = "Character.ma_wat_lch_01_outpost_miniboss" },
        { name = "Yelena Sidorova", record = "Character.ma_wat_nid_01_outpost_miniboss" },
        { name = "Scav Netrunner", record = "Character.mq002_scavenger_netrunner" },
        { name = "Arasaka VR Robot", record = "Character.q000_tutorial_course_04_fistfigher_full_fists" },
        { name = "Dead Man", record = "Character.q001_scavenger_dead_man" },
        { name = "Arasaka Netrunner", record = "Character.arasaka_netrunner_netrunner2_yukimura_ma_rare" },
        { name = "Susan Abernathy", record = "Character.q000_corpo_abernathy" },
        { name = ">>Slice543<<", record = "Character.q000_corpo_netrunner" },
        { name = "Cynthia Najarro", record = "Character.mq040_wife" },
        { name = "Jermaine Norton", record = "Character.Riot_Bouncer" },
        { name = "Caliente Waitress", record = "Character.sq017_caliente_waitress" },
        { name = "Caliente Cook", record = "Character.sq017_caliente_staff" },
        { name = "Filipino Barista", record = "Character.sq017_filipino_barista" },
        { name = "Linda Spencer", record = "Character.mq019_fa_club_staff" },
        { name = "Ralph Logan", record = "Character.Riot_Barman" },
        { name = "Rebeca Price", record = "Character.sts_hey_spr_06_rebeca_price" },
        { name = "José Luis", record = "Character.sts_hey_spr_01_jose" },
        { name = "Karubo Barei", record = "Character.sts_hey_rey_08_karubo" },
        { name = "Gustavo Orta", record = "Character.sts_hey_rey_01_gustavo" },
        { name = "El Gallo", record = "Character.sts_hey_gle_05_el_gallo" },
        { name = "Valentino Funeral", record = "Character.sq018_ma_valentinos" },
        { name = "Isabella Fuscino", record = "Character.sq018_gle_01_mom" },
        { name = "Marlon Fuscino", record = "Character.sq018_gle_01_dad" },
        { name = "Zoe Alonzo", record = "Character.ma_hey_gle_02_outpost_miniboss" },
        { name = "Miguel Rodrigez", record = "Character.ma_hey_rey_06_outpost_miniboss" },
        { name = "Denzel Cryer", record = "Character.ma_hey_spr_11_outpost_miniboss" },
        { name = "Darius Miles", record = "Character.ma_std_arr_03_outpost_miniboss" },
        { name = "Olga Elisabeth Longmead", record = "Character.ma_std_rcr_08_outpost_miniboss" },
        { name = "Mokomichi 'Motorboy' Yamada", record = "Character.ma_wat_lch_08_outpost_miniboss" },
        { name = "Tom Ayer", record = "Character.ma_wat_nid_02_outpost_miniboss" },
        { name = "Kaiser Herzog", record = "Character.ma_wat_nid_06_outpost_miniboss" },
        { name = "Tyger Claw Bodyguard", record = "Character.ma_wbr_jpn_20_miniboss_bodyguard1" },
        { name = "Shinobu Imai", record = "Character.ma_wbr_jpn_20_outpost_miniboss" },
        { name = "Gallus Gallus Domesticus", record = "Character.q110_cage_chicken" },
        { name = "Henry Sanchez", record = "Character.q204_steves_dad" },
        { name = "Jill Sanchez", record = "Character.q204_steves_mom" },
        { name = "Drausin", record = "Character.sq011_drausin" },
        { name = "Kerry's Security Bot", record = "Character.sq011_kerry_bot" },
        { name = "Cow", record = "Character.sq021_fake_cow_npc" },
        { name = "Walt Ozark", record = "Character.sts_wbr_jpn_09_walt_ozark" },
        { name = "Teddy Simos", record = "Character.Teddy" },
        { name = "Tom Caldera", record = "Character.Tom" },
        { name = "Hover V", record = "Character.TPP_Player_Cutscene" },
        { name = "Tsutomu", record = "Character.Tsutomu" },
        { name = "Unknown Voice", record = "Character.unknown_voice" },
        { name = "Zane Jagger", record = "Character.Zane_Jagger" },
        { name = "Ogawa", record = "Character.Ogawa" },
        { name = "Oliver Fernandez", record = "Character.oliver_fernandez" },
        { name = "News Anchor", record = "Character.towfiq_iqbal" },
        { name = "Stefan", record = "Character.mq036_stefan" },
        { name = "Bhikkhu", record = "Character.mq032_monk_brother" },
        { name = "Bhikkhu's Brother", record = "Character.mq032_monk_cyberware" },
        { name = "Colonel Cross", record = "Character.main_boss_ColonelCross" },
        { name = "Coach Fred", record = "Character.wat_lch_melee_01" },
        { name = "Oda", record = "Character.Cyberninja_Oda_Follower" },
        { name = "Angel", record = "Character.q105_doll_male_angel" },
        { name = "Henry Stints", record = "Character.q000_kid_parking_stints" },
        { name = "Rita Wheeler", record = "Character.lizzies_bouncer" },
        { name = "Secret Ripperdoc", record = "Character.wat_kab_ripperdoc_01" },
        { name = "William Hare", record = "Character.sts_wat_kab_03_solo" },
        { name = "Female MaxTac Soldier", record = "Character.prevention_maxtac_rifle_wa" },
        { name = "Scavenger Boss", record = "Character.q001_scavenger_boss" },
        { name = "Joseph", record = "Character.mq040_corpo" },
        { name = "Delamain Drone", record = "Character.sq025_delamain_drone_bombus_speaker" },
        { name = "Drug Dealer", record = "Character.q000_hym_ma" },
        { name = "VR Tutorial Skull", record = "Character.q000_tutorial_course_04_skull" },
        { name = "Big Pete", record = "Character.ina_02_new_big_pete" },
        { name = "Ivan Guerreiro", record = "Character.ivan_guerreiro" },
        { name = "Jim Jarry", record = "Character.jim_jarry" },
        { name = "Nibbles", record = "Character.q003_cat" },
        { name = "Kovachek", record = "Character.kovachek" },
        { name = "Wakako's Driver", record = "Character.ow_wakako_driver" },
        { name = "Bouncer", record = "Character.Bouncer" },
        { name = "Female Arasaka Driver", record = "Character.CorpoWomanArasakaDriver" },
        { name = "Sergei", record = "Character.ma_cct_dtn_03_scav_driver" },
        { name = "Rogue's Driver", record = "Character.ow_rogue_driver" },
        { name = "Prof. Sachiko Kusama", record = "Character.q201_doctor_scientist" },
        { name = "Male Stripper", record = "Character.sq025_reg_stripper_ma" },
        { name = "Johnny Mirror (Invisible)", record = "Character.johnny_mirror" },
        { name = "Corpo Mox Bouncer", record = "Character.q000_corpo_mox_bouncer" },
        { name = "Delamain", record = "Character.Delamain" },
        { name = "Max Jones", record = "Character.sts_wat_nid_12_max_jones" },
        { name = "Croupier", record = "Character.sts_wat_kab_07_croupiers" },
        { name = "Male Rich", record = "Character.CitizenRichMaleCasual" },
        { name = "Male Waiter", record = "Character.CookMale" },
        { name = "Female Samurai Fan", record = "Character.q108_samurai_fan_fa" },
        { name = "Female Japantown Quest", record = "Character.LightCrowd_japantown_wa_quest" },
        { name = "Paparazzi", record = "Character.mq028_stalker" },
        { name = "Royce (Boss Version)", record = "Character.main_boss_royce" },
        { name = "Pimp", record = "Character.q105_jigjig_pimp" },
        { name = "Female Afterlife Walker", record = "Character.q005_afterlife_walker_male_02_female" },
        { name = "Female Santo Domingo Crowd", record = "Character.sq024_santo_domingo_crowd_female" },
        { name = "Female Afterlife Crowd", record = "Character.q103_afterlife_crowd_female" },
        { name = "Konpeki Plaza Concierge", record = "Character.q005_hotel_concierge" },
        { name = "Konpeki Plaza Janitor", record = "Character.q005_hotel_janitor" },
        { name = "Konpeki Plaza Waitress", record = "Character.q005_hotel_waitress" },
        { name = "Konpeki Plaza Bartender", record = "Character.q005_hotel_bartender" },
        { name = "Konpeki Plaza Receptionist", record = "Character.q005_hotel_receptionist" },
        { name = "Konpeki Plaza Guest", record = "Character.q005_hotel_guest_male" },
        { name = "Soulkiller Agent", record = "Character.q101_arasaka_soulkilling_agents" },
        { name = "Tasha Rodriquez (Cyberface)", record = "Character.q105_fingers_patient" },
        { name = "Peter Horvath (Psycho)", record = "Character.sq012_assassin" },
        { name = "Taxi Assassin 1", record = "Character.taxiAssassin_001" },
        { name = "Meghan Hattori (Tourist)", record = "Character.mq026_tourist_01" },
        { name = "Airi Okawa (Tourist)", record = "Character.mq026_tourist_02" },
        { name = "Taxi Assassin 2", record = "Character.taxiAssassin_002" },
        { name = "Taxi Assassin 3", record = "Character.taxiAssassin_003" },
        { name = "Liam Northom", record = "Character.mq019_liam" },
        { name = "Asa Risu (Technician)", record = "Character.mq019_technician" },
        { name = "Quest Ripperdoc", record = "Character.pac_wwd_ripdoc_01" },
        { name = "Pachinko Bouncer", record = "Character.sq017_pachinko_doorman" },
        { name = "BD Thug 1", record = "Character.q004_bd_tut_thug_01" },
        { name = "BD Thug 2", record = "Character.q004_bd_tut_thug_02" },
        { name = "Male Homeless Fat", record = "Character.mq003_homeless_fat" },
        { name = "Ken Lee (Loser)", record = "Character.mq009_loser" },
        { name = "River's Neighbor", record = "Character.sq029_neighbor_01" },
        { name = "Arasaka Seller", record = "Character.mq015_seller" },
        { name = "Diner Owner", record = "Character.mq022_bar_owner" },
        { name = "Street Musician", record = "Character.mq023_bootleg_performer" },
        { name = "Buck Arnold", record = "Character.mq025_buck" },
        { name = "Male Pacifica Dirty", record = "Character.mq025_pacifica_male" },
        { name = "Sue Glover (Disciple)", record = "Character.mq026_disciple" },
        { name = "Male Maelstrom Elite", record = "Character.mq026_mal_tank" },
        { name = "Man in Black", record = "Character.mq026_smuggler" },
        { name = "Woman in Black", record = "Character.mq026_smuggler_boss" },
        { name = "Suicide Stan", record = "Character.mq027_driver" },
        { name = "BD Recorder", record = "Character.mq027_recorder" },
        { name = "Herring Man", record = "Character.mq028_herring_man" },
        { name = "Old Creep", record = "Character.mq028_herring_old" },
        { name = "Male Corpo Big", record = "Character.mq030_corpoManBig_crowd" },
        { name = "Cyberpsycho (Quest)", record = "Character.mq030_cyberpsycho" },
        { name = "Jinguji Bodyguard", record = "Character.mq030_jinguji_bodyguard_1" },
        { name = "Clerk", record = "Character.mq037_clerk" },
        { name = "Old Elliot (Roadhouse)", record = "Character.q000_roadhouse_town_trainer" },
        { name = "Local (Roadhouse)", record = "Character.q000_roadhouse_town_weightlifter" },
        { name = "Elderly Lady", record = "Character.q001_old_lady" },
        { name = "Trauma Team Pilot", record = "Character.q101_pilot" },
        { name = "Alexandre Batisma (Contact)", record = "Character.q110_contact" },
        { name = "Cook", record = "Character.q112_market_cook" },
        { name = "Zuleikha El Ahmar", record = "Character.sq023_mariah" },
        { name = "Elderly Man", record = "Character.q112_chairman" },
        { name = "Olga Cygan (BD Director)", record = "Character.sq023_bd_director" },
        { name = "Assault Squad Commander", record = "Character.q005_arasaka_kill_squad_4_officer" },
        { name = "Konpeki Plaza Doorman", record = "Character.q005_hotel_doorman" },
        { name = "Bartolomeo Mordellini", record = "Character.q005_mordelinii" },
        { name = "Camera Operator", record = "Character.q103_afterlife_extras" },
        { name = "Kang Tao Paramedic", record = "Character.q104_kang_paramedic" },
        { name = "Lowlife Bouncer", record = "Character.q108_bodyguard_male" },
        { name = "Male Voodoo Netrunner", record = "Character.q110_tineptune" },
        { name = "Elder Netrunner 1", record = "Character.q110_vdb_elder_1" },
        { name = "Elder Netrunner 2", record = "Character.q110_vdb_elder_2" },
        { name = "Elder Netrunner 4", record = "Character.q110_vdb_elder_4" },
        { name = "Elder Netrunner 5", record = "Character.q110_vdb_elder_5" },
        { name = "Elder Netrunner 3", record = "Character.q110_vdb_elder_3" },
        { name = "Camera Drone", record = "Character.q112_camera_drone" },
        { name = "Panam FPP", record = "Character.sq027_panam_fpp" },
        { name = "Male Aldecaldo Big", record = "Character.CitizenAldecaldosMaleBig" },
        { name = "Jake Scooter", record = "Character.mq021_nomad_scooter" },
        { name = "Valentino Machete", record = "Character.gle_valentinos_machete_hmelee3_machete_mb_elite" },
        { name = "Valentino Elite", record = "Character.rey_valentinos_elite3_ranged3_dual_ma_elite" },
        { name = "Valentino Shotgun", record = "Character.rey_valentinos_shotgun3_shotgun3_testera_ma_elite" },
        { name = "Valentino Baseball", record = "Character.rey_valentinos_grunt1_melee1_baseball_wa" },
        { name = "Valentino Nova", record = "Character.spr_valentinos_grunt1_ranged1_nova_wa" },
        { name = "Voodoo Boy Elite", record = "Character.voodooboys_grunt3coat_shotgun3_zhuo_ma_elite" },
        { name = "Voodoo Girl Ranged", record = "Character.voodooboys_grunt1_ranged2_sidewinder_wa" },
        { name = "Voodoo Boy Baseball", record = "Character.voodooboys_grunt1_fmelee2rare_baseball_ma_rare" },
        { name = "Male Big Melee", record = "Character.jpn_tyger_claws_ozeki_hmelee3_kanabo_mb" },
        { name = "Female Katana", record = "Character.jpn_tyger_claws_kunoichi_fmelee3_katana_wa_elite" },
        { name = "Male Katana", record = "Character.kab_tyger_claws_martial_fmelee2_katana_ma_rare" },
        { name = "Male Ranged", record = "Character.kab_tyger_claws_biker2_ranged2_shingen_ma" },
        { name = "Female Ranged", record = "Character.kab_tyger_claws_biker2_ranged2_shingen_wa" },
        { name = "Roadie Club", record = "Character.sq017_roadie_club" },
        { name = "Blake Croyle", record = "Character.kab_06_Blake" },
        { name = "Robert Wilson", record = "Character.Wilson" },
        { name = "Noah", record = "Character.bls_ina_se1_foodshop_01" },
        { name = "Bob", record = "Character.Bob" },
        { name = "Roxanne Colton", record = "Character.q108_mercenary_f_01_deal_chat" },
        { name = "Kimiko Sanchez", record = "Character.q108_mercenary_f_02_deal_chat" },
        { name = "VR Tutorial Dummy", record = "Character.q000_tutorial_course_01_patroller" },
        { name = "6th Leader", record = "Character.q000_kid_hostile_ganger_01" },
        { name = "Roger Wang", record = "Character.wat_kab_medicstore_01" },
        { name = "Chang Hoon Nam", record = "Character.sts_wbr_jpn_05_chang_hoon_nam" },
        { name = "Zen Master", record = "Character.mq014_master.ent" },
        { name = "Fredrik Persson", record = "Character.sts_wat_nid_04_fredrik" },
    }
end
